export const GlobalVariables = {
  noDataLength: 0,
  emptyString: '',
  plus: '+',
  required: '*',
  percentage: '%',
  imageURL: 'https://api.dicebear.com/8.x/adventurer/svg?seed=',
  pagination: {
    elementsPerPage: { min: 25, median: 50, max: 100 },
    rowsPerPage: 10,
    firstPage: 1,
  },
  manyDataLength: 2,
  dateFormats: {
    Day: 'DD',
    Month: 'MMM',
    DefaultFormat: 'DD/MM/YYYY',
    DefaultFormatShort: 'DD/MM/YY',
    DefaultFormatWithTime: 'DD/MM/YYYY HH:mm',
    DefaultFormatWithTimeWithDash: 'DD/MM/YYYY - HH:mm',
    DefaultStringFormatWithTime: 'DD/MM/YYYY - HH[h]mm',
    StringDateFormatShortDayWithTime: 'DD MMMM YYYY - HH[h]mm',
    StringDateFormatWithTime: 'dddd D MMMM YYYY - HH[h]mm',
    StringDateFormat: 'dddd DD MMMM',
    StringDateFormatWithYear: 'dddd DD MMMM YYYY',
    PointsDateFormat: 'DD.MM.YY',
    YearFormat: 'YYYY',
    MonthFormat: 'MMMM YYYY',
    TextFormat: 'DD MMM YYYY',
    FullTextFormat: 'DD MMMM YYYY',
    TimeFormat: 'HH:mm',
    TimeFormat2: 'HH[h]mm',
    TimeSecondsFormat: 'HH:mm:ss',
    TimeMinuteAndSecondsFormat: 'mm:ss',
    FullDateFormat: 'dddd DD MMMM YYYY',
    ISO8601DateFormat: 'YYYY-MM-DDT',
    ISO8601DateFormatWithTime: 'YYYY-MM-DDTHH:mm',
    MonthYearFormat: 'MMMM YYYY',
    WeekDateFormat: 'dddd D',
    DayMonthFormat: 'DD MMMM',
    DayMonthWithSlashFormat: 'DD/MM',
    FullMonthFormat: 'MMMM',
    TimeFormat12Hour: 'hh:mm A',
  },
  regex: {
    name: /^[a-zA-Z]+$/,
    age: /^[1-9]\d*$/,
    number: /[^0-9.]/g,
    email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    // At least one digit // At least one lowercase letter // At least one uppercase letter // At least 8 characters long.
    password: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/,
    phone: /^[+]?[(]?[0-9]{3}[)]?[-\s.]?[0-9]{3}[-\s.]?[0-9]{4,6}$/,
    username: /^[a-zA-Z0-9_.]{3,16}$/,
  },

  alerts: {
    defaultDuration: 5000,
  },
};
